BEGIN;
UPDATE leads SET phone = '+12148289690', updated_at = now() WHERE name = 'P V Auto Services' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+13178928182', updated_at = now() WHERE name = 'We Can Clean That' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+15053595066', updated_at = now() WHERE name = 'Waste Removal - Albuquerque Dumpster Rentals' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19013360241', updated_at = now() WHERE name = 'Tech Life Appliance Repair' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19014896495', updated_at = now() WHERE name = 'R G Appliances' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+15026492991', updated_at = now() WHERE name = 'Fuqua Fence' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19802985785', updated_at = now() WHERE name = 'Kings Power Washing of Charlotte' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+18449698727', updated_at = now() WHERE name = 'Maclin''s A/C & Appliance Service' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+15053287389', updated_at = now() WHERE name = 'Daniel Trujillo Dump Truck' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+15054506265', updated_at = now() WHERE name = 'Unlimited Waste' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17049916296', updated_at = now() WHERE name = 'Queen City Pressure Washing' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19014281991', updated_at = now() WHERE name = 'Norwood Used Appliance and Repair' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+15055388101', updated_at = now() WHERE name = 'Comet Dumspter Rental Santa Fe' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19014877882', updated_at = now() WHERE name = 'Cjs Used Appliances' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17136920038', updated_at = now() WHERE name = 'Finest Auto Body and Paint LLC' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12818241760', updated_at = now() WHERE name = 'Santa Ana Body Shop' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17137894130', updated_at = now() WHERE name = 'Leo''s Body Shop' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12819333706', updated_at = now() WHERE name = 'Cho''s Auto Body Shop' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17137299599', updated_at = now() WHERE name = 'Brookston Body Shop BBS' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17134409100', updated_at = now() WHERE name = 'Regency Auto Repair & Body Shop' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17137856533', updated_at = now() WHERE name = 'Master Auto Body & Upholstery' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17138620709', updated_at = now() WHERE name = 'Manriquez Collision & Mechanic Shop' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17138626630', updated_at = now() WHERE name = 'Master Car Care & Collision' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17136802266', updated_at = now() WHERE name = 'Caliber Collision' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+18325531760', updated_at = now() WHERE name = 'Javiers Auto Body' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+18325084163', updated_at = now() WHERE name = 'Montes Collision Repair' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+18329171707', updated_at = now() WHERE name = 'Filam Auto & Body Repair' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+18326886389', updated_at = now() WHERE name = 'Metropolitan Collision' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17139739100', updated_at = now() WHERE name = 'Best Collision Center' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12107342050', updated_at = now() WHERE name = 'AT Automotive' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17136623649', updated_at = now() WHERE name = 'TOB Auto Body Repair Shop' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17139786272', updated_at = now() WHERE name = 'G-Man Automotive & Body Shop' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12109609482', updated_at = now() WHERE name = 'Kingdom Auto Repair Service' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17136683639', updated_at = now() WHERE name = 'Uptown Automotive Auto Body Shop Repair' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+18324391254', updated_at = now() WHERE name = 'Calcena body shop' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12106401908', updated_at = now() WHERE name = 'Eurasian Auto Repair' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12103132030', updated_at = now() WHERE name = 'VIP Mobile Mechanic' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17132669800', updated_at = now() WHERE name = 'Royal Collision Auto Paint & Body Shop' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+18322654432', updated_at = now() WHERE name = '290 Auto Repair & Body Shop' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12103411171', updated_at = now() WHERE name = 'Seymour''s Garage' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12109223333', updated_at = now() WHERE name = 'Mr. Mechanic & Tire Muffler Shop' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12817049779', updated_at = now() WHERE name = 'David''s Auto Collision' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12104001000', updated_at = now() WHERE name = 'Sam''s Hybrid Auto Repair' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12104956688', updated_at = now() WHERE name = 'Auto Service Experts' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17133492886', updated_at = now() WHERE name = 'JJ Auto Body' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12109609810', updated_at = now() WHERE name = 'Christian Brothers Automotive Alamo Heights' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17132235231', updated_at = now() WHERE name = 'Texas Auto Repair & Body Shop' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12105200608', updated_at = now() WHERE name = 'Goose Euro - Downtown' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12107371277', updated_at = now() WHERE name = 'Jackie''s Auto Clinic' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+18324443005', updated_at = now() WHERE name = 'Car Body Repair by Car Body Club' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12107619999', updated_at = now() WHERE name = 'Aspeed Auto Repair' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12815462370', updated_at = now() WHERE name = 'Jimmy''s Auto Repair Body' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12106141444', updated_at = now() WHERE name = 'A Good Mechanic' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12109077395', updated_at = now() WHERE name = 'Sun Auto Tire & Service' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17133937802', updated_at = now() WHERE name = 'Elevated Auto & Collision' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12107963844', updated_at = now() WHERE name = 'NuBrakes Mobile Brake Repair' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17136992430', updated_at = now() WHERE name = 'JOE''S BODY SHOP' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12103422083', updated_at = now() WHERE name = 'Thrash Automotive' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12108622823', updated_at = now() WHERE name = 'USA Auto Repair' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17138021168', updated_at = now() WHERE name = 'U.S. Auto Connection' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12104900086', updated_at = now() WHERE name = 'Goose Auto Repair' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17138089875', updated_at = now() WHERE name = 'IMPERIAL COLLISION SPECIALIST' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17262685866', updated_at = now() WHERE name = 'Surgo Automotive' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12107241313', updated_at = now() WHERE name = 'AA Auto Repair' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17137470268', updated_at = now() WHERE name = 'Mr. Joe & Son Body Shop' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12104942502', updated_at = now() WHERE name = 'Your Mechanic' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12109401181', updated_at = now() WHERE name = 'Paleo Car Care' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17135234774', updated_at = now() WHERE name = 'River Oaks Paint & Body' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12102236500', updated_at = now() WHERE name = 'Mike''s Downtown Garage' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12108588507', updated_at = now() WHERE name = 'Larson''s Automotive' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17136915995', updated_at = now() WHERE name = 'ABS Auto Body Specialists' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12106804328', updated_at = now() WHERE name = 'AutoWorks' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12109341582', updated_at = now() WHERE name = 'Chad Miller Auto Care' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12106071896', updated_at = now() WHERE name = 'Intune mobile mechanic' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12104642406', updated_at = now() WHERE name = 'Texas Auto Repairs' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12103401510', updated_at = now() WHERE name = 'Goose Euro - West Ave' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12108240642', updated_at = now() WHERE name = 'Broadway Tire & Automotive' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12104181397', updated_at = now() WHERE name = 'Ewing Automotive' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12107631955', updated_at = now() WHERE name = 'Roy''s Mobile Mechanic' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12107335500', updated_at = now() WHERE name = 'Babcock Automotive' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12108991555', updated_at = now() WHERE name = 'John''s Auto Repair' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12104813330', updated_at = now() WHERE name = 'Belden''s Automotive & Tires' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+12106979600', updated_at = now() WHERE name = 'Cambridge Auto Center, Inc.' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17028783770', updated_at = now() WHERE name = 'Hair Of The Dog Grooming Salon' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17253049853', updated_at = now() WHERE name = 'Paw Wow' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17252050905', updated_at = now() WHERE name = 'Suds N Bubbles' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17025869600', updated_at = now() WHERE name = 'Barks and Bubbles Salon & Mobile Pet Grooming' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17028048788', updated_at = now() WHERE name = 'PAWlish Pet Salon & Mobile Grooming' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17028055412', updated_at = now() WHERE name = 'Well Groomed Pets Summerlin' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17022660303', updated_at = now() WHERE name = 'Royalty Paw Grooming' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17023997827', updated_at = now() WHERE name = 'Doug King’s Pup Star Pet Salon' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17022483647', updated_at = now() WHERE name = 'Las vegas zen Dog grooming' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17023953647', updated_at = now() WHERE name = 'Groomer Has It' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17027207655', updated_at = now() WHERE name = 'Pretty Paws Pet Grooming' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17028865678', updated_at = now() WHERE name = 'PinkPaw Pet Salon' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17029311778', updated_at = now() WHERE name = 'Pawsh Palace' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17028733341', updated_at = now() WHERE name = 'Tailwaggers Pet Grooming' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17023801720', updated_at = now() WHERE name = 'Lucky''s Pet Grooming & Boutique' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17028736555', updated_at = now() WHERE name = 'A Doggie''s Delight' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19012565271', updated_at = now() WHERE name = 'Memphis Veterinary Specialists' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17022551565', updated_at = now() WHERE name = 'Man''s Best Friend' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17028480691', updated_at = now() WHERE name = 'Groom Room' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17022479274', updated_at = now() WHERE name = 'Barking Dogs Self-Wash & Grooming Mountains Edge' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17027134026', updated_at = now() WHERE name = 'Hair of the dog Nellis' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17027780411', updated_at = now() WHERE name = 'Desert Doggies Grooming' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19013240202', updated_at = now() WHERE name = 'The Pet Hospitals' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19013889550', updated_at = now() WHERE name = 'Raleigh Bartlett Animal Hospital' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19012727411', updated_at = now() WHERE name = 'Memphis Animal Clinic' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19013772244', updated_at = now() WHERE name = 'Hillcrest Animal Hospital' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19016836339', updated_at = now() WHERE name = 'Eastgate Animal Clinic' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19013174414', updated_at = now() WHERE name = 'East Memphis Pet Hospital & Resort' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17024768640', updated_at = now() WHERE name = 'Happy And Lucky Pet Salon And Mobile Grooming.' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19016822791', updated_at = now() WHERE name = 'Summer Avenue Animal Hospital' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19016825681', updated_at = now() WHERE name = 'Cloverleaf Animal Clinic' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19017468758', updated_at = now() WHERE name = 'Utopia Animal Hospital' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17022687384', updated_at = now() WHERE name = 'Barking Dogs Self Wash & Grooming Centennial Hills' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17024735409', updated_at = now() WHERE name = 'Piggy Tails Pet Spa & More' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19013722215', updated_at = now() WHERE name = 'Shelby Center Hospital for Animals' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19013719653', updated_at = now() WHERE name = 'Wolfchase Animal Hospital' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19014523171', updated_at = now() WHERE name = 'Southern Crossing Animal Hospital' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17028185647', updated_at = now() WHERE name = 'Best In Show' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17028904974', updated_at = now() WHERE name = 'SOS Dog Grooming' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19013628321', updated_at = now() WHERE name = 'Southwind Animal Hospital' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19013589111', updated_at = now() WHERE name = 'Northgate Animal Hospital' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17755230227', updated_at = now() WHERE name = 'Pet Story' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17022342105', updated_at = now() WHERE name = 'Calling All Paws' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17024576246', updated_at = now() WHERE name = 'Shaggy Shaggy Shake' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17028020085', updated_at = now() WHERE name = 'Z Dog Grooming' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17252335012', updated_at = now() WHERE name = 'Lovely Dog Services.' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17026723531', updated_at = now() WHERE name = 'Majestic Mutts' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17028787877', updated_at = now() WHERE name = 'Las Vegas Pet Spa' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17252460200', updated_at = now() WHERE name = 'Well Groomed Pets Las Vegas' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19012564595', updated_at = now() WHERE name = 'Animal Emergency Center' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17022023333', updated_at = now() WHERE name = 'Desert Pet Spa' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19016825684', updated_at = now() WHERE name = 'McGehee Clinic For Animals' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+17026084649', updated_at = now() WHERE name = 'Punky Pets Pawlor LLC' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19013243202', updated_at = now() WHERE name = 'Spay Memphis' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19013231177', updated_at = now() WHERE name = 'Walnut Grove Animal Clinic' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19013772330', updated_at = now() WHERE name = 'Community Pet Hospital' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19012741444', updated_at = now() WHERE name = 'Central Animal Hospital' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19015901230', updated_at = now() WHERE name = 'Grace Animal Hospital' AND (phone IS NULL OR phone = '');
UPDATE leads SET phone = '+19012075879', updated_at = now() WHERE name = 'PetVax Complete Care Centers - East Memphis' AND (phone IS NULL OR phone = '');
COMMIT;