"""=AWS Agent Skills — aws's OWN brain, loaded from its repo-local folder.

AWS cloud infra & deployment agent. Its skills live in admin/agency/aws_skills_repo/ (repo-local, deploys to
AWS with the agent). Detect by keyword -> load from own folder -> inject as context.
Generated by register_agent(); edit the registry below to tune keywords.
"""

from __future__ import annotations

import logging

from agent_skill_loader import (
    detect_agent_skills,
    build_agent_skill_context,
    list_agent_skills,
)

logger = logging.getLogger(__name__)

AGENT_NAME = "aws"

AWS_SKILL_REGISTRY: list[dict] = [
    {
        "name": "aws-cdk",
        "keywords": [
            "aws-cdk",
        ],
        "description": "aws-cdk skill for the aws agent",
    },
    {
        "name": "aws-serverless",
        "keywords": [
            "aws-serverless",
        ],
        "description": "aws-serverless skill for the aws agent",
    },
    {
        "name": "aws-security",
        "keywords": [
            "aws-security",
        ],
        "description": "aws-security skill for the aws agent",
    },
]


def detect_skills(message: str, max_skills: int = 2) -> list[dict]:
    """Detect relevant aws skills from a message (loaded from aws_skills_repo/)."""
    return detect_agent_skills(AGENT_NAME, message, AWS_SKILL_REGISTRY, max_skills=max_skills)


def build_skill_context(skills: list[dict]) -> str:
    """Build the aws skill context block."""
    return build_agent_skill_context(skills)


def list_aws_skills() -> list[dict]:
    """List aws's own skills (without loading content)."""
    return list_agent_skills(AGENT_NAME, AWS_SKILL_REGISTRY)
