"""Kaggle GPU Tools — image and video generation using Kaggle API.

Uses Kaggle API to submit GPU notebooks for:
  - FLUX (image generation)
  - CogVideoX (video generation)

All free with Kaggle account (30hrs/week GPU quota).

Two modes:
  1. Direct API submission (if kaggle CLI is installed)
  2. Notebook code generation (fallback — user runs manually)
"""
from __future__ import annotations

import json
import logging
import os
import subprocess
import time
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


# ═══════════════════════════════════════════════════════════════════════════════
# KAGGLE API SETUP
# ═══════════════════════════════════════════════════════════════════════════════

def _check_kaggle() -> bool:
    """Check if Kaggle CLI is installed and configured."""
    try:
        result = subprocess.run(
            ["kaggle", "--version"],
            capture_output=True, text=True, timeout=10
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def _get_kaggle_creds() -> dict[str, str]:
    """Get Kaggle credentials from environment or kaggle.json."""
    username = os.getenv("KAGGLE_USERNAME", "")
    key = os.getenv("KAGGLE_KEY", "")

    if not username or not key:
        kaggle_json = os.path.expanduser("~/.kaggle/kaggle.json")
        if os.path.exists(kaggle_json):
            with open(kaggle_json) as f:
                creds = json.load(f)
                username = creds.get("username", "")
                key = creds.get("key", "")

    return {"username": username, "key": key}


def _run_kaggle_cmd(args: list[str], timeout: int = 30) -> dict[str, Any]:
    """Run a kaggle CLI command and return result."""
    try:
        result = subprocess.run(
            ["kaggle"] + args,
            capture_output=True, text=True, timeout=timeout
        )
        return {
            "success": result.returncode == 0,
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
        }
    except FileNotFoundError:
        return {"success": False, "error": "kaggle CLI not installed"}
    except subprocess.TimeoutExpired:
        return {"success": False, "error": "Command timed out"}


# ═══════════════════════════════════════════════════════════════════════════════
# 1. IMAGE GENERATION (FLUX)
# ═══════════════════════════════════════════════════════════════════════════════

FLUX_NOTEBOOK_SOURCE = '''# Auto-generated by TAGS Content Agent
# FLUX Image Generation on Kaggle GPU

!pip install diffusers transformers accelerate safetensors -q

import torch
from diffusers import FluxPipeline
from PIL import Image
import json, os

# Load FLUX model
pipe = FluxPipeline.from_pretrained(
    "black-forest-labs/FLUX.1-dev",
    torch_dtype=torch.bfloat16
)
pipe.enable_model_cpu_offload()

# Generate image
PROMPT = "{prompt}"
WIDTH = {width}
HEIGHT = {height}
STEPS = {steps}

image = pipe(
    PROMPT,
    width=WIDTH,
    height=HEIGHT,
    num_inference_steps=STEPS,
    guidance_scale=3.5,
).images[0]

output_path = "output.png"
image.save(output_path)
print(json.dumps({{
    "status": "success",
    "output_file": output_path,
    "resolution": f"{{WIDTH}}x{{HEIGHT}}",
    "prompt": PROMPT,
    "steps": STEPS
}}))
'''


def _build_flux_notebook(prompt: str, width: int, height: int, steps: int) -> dict[str, Any]:
    """Build a Kaggle-format notebook JSON for FLUX image generation."""
    source = FLUX_NOTEBOOK_SOURCE.format(
        prompt=prompt.replace('"', '\\"'),
        width=width,
        height=height,
        steps=steps,
    )
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kaggle": {
                "accelerator": "gpu",
                "dataSources": [],
                "isGpuEnabled": True,
                "isInternetEnabled": True,
                "language": "python",
            },
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
        },
        "cells": [
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": source.split("\n"),
            }
        ],
    }
    return notebook


def generate_image_kaggle(
    prompt: str,
    width: int = 1024,
    height: int = 1024,
    steps: int = 20,
) -> dict[str, Any]:
    """Generate image using FLUX on Kaggle GPU.

    If kaggle CLI is available, submits the notebook directly.
    Otherwise, returns notebook code for manual submission.
    """
    if not _check_kaggle():
        return {
            "status": "notebook_ready",
            "tool": "FLUX",
            "prompt": prompt,
            "resolution": f"{width}x{height}",
            "steps": steps,
            "estimated_time": "~30-60 seconds on T4 GPU",
            "notebook": _build_flux_notebook(prompt, width, height, steps),
            "notebook_code": FLUX_NOTEBOOK_SOURCE.format(
                prompt=prompt, width=width, height=height, steps=steps
            ),
            "message": "Kaggle CLI not found. Notebook ready for manual upload.",
            "setup": "pip install kaggle && kaggle config path ~/.kaggle/kaggle.json",
        }

    # Submit via Kaggle API
    creds = _get_kaggle_creds()
    if not creds["username"]:
        return {
            "status": "setup_required",
            "message": "Kaggle credentials not found",
            "setup_steps": [
                "Get API key from kaggle.com/settings",
                "Set KAGGLE_USERNAME and KAGGLE_KEY env vars",
                "Or save to ~/.kaggle/kaggle.json",
            ],
            "notebook_code": FLUX_NOTEBOOK_SOURCE.format(
                prompt=prompt, width=width, height=height, steps=steps
            ),
        }

    # Create temp notebook and submit
    import tempfile
    notebook_data = _build_flux_notebook(prompt, width, height, steps)
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".ipynb", delete=False, dir=tempfile.gettempdir()
    ) as f:
        json.dump(notebook_data, f)
        tmp_path = f.name

    try:
        result = _run_kaggle_cmd(
            ["kernels", "push", "-p", tmp_path, "-t", "gpu"],
            timeout=30,
        )
        if result["success"]:
            kernel_slug = f"{creds['username']}/tags-flux-{int(time.time())}"
            return {
                "status": "submitted",
                "tool": "FLUX",
                "prompt": prompt,
                "resolution": f"{width}x{height}",
                "steps": steps,
                "estimated_time": "~30-60 seconds on T4 GPU",
                "kernel_slug": kernel_slug,
                "message": "Notebook submitted to Kaggle. Check status with kaggle kernels status.",
                "check_status": f"kaggle kernels status {kernel_slug}",
            }
        else:
            return {
                "status": "submit_failed",
                "error": result.get("stderr", result.get("error", "Unknown error")),
                "notebook_code": FLUX_NOTEBOOK_SOURCE.format(
                    prompt=prompt, width=width, height=height, steps=steps
                ),
            }
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass


# ═══════════════════════════════════════════════════════════════════════════════
# 2. VIDEO GENERATION (CogVideoX)
# ═══════════════════════════════════════════════════════════════════════════════

COGVIDEO_NOTEBOOK_SOURCE = '''# Auto-generated by TAGS Content Agent
# CogVideoX Video Generation on Kaggle GPU

!pip install diffusers transformers accelerate imageio[ffmpeg] -q

import torch
from diffusers import CogVideoXPipeline
import imageio, json

# Load CogVideoX model
pipe = CogVideoXPipeline.from_pretrained(
    "THUDM/CogVideoX-5b",
    torch_dtype=torch.bfloat16
)
pipe.enable_model_cpu_offload()

# Generate video
PROMPT = "{prompt}"
NUM_FRAMES = {frames}

video = pipe(
    PROMPT,
    num_videos_per_prompt=1,
    num_inference_steps=50,
    num_frames=NUM_FRAMES,
    guidance_scale=6.0,
).videos[0]

output_path = "output.mp4"
imageio.mimsave(output_path, video, fps=8)
print(json.dumps({{
    "status": "success",
    "output_file": output_path,
    "frames": NUM_FRAMES,
    "duration_seconds": round(NUM_FRAMES / 8, 1),
    "prompt": PROMPT
}}))
'''


def _build_cogvideo_notebook(prompt: str, frames: int) -> dict[str, Any]:
    """Build a Kaggle-format notebook JSON for CogVideoX video generation."""
    source = COGVIDEO_NOTEBOOK_SOURCE.format(
        prompt=prompt.replace('"', '\\"'),
        frames=frames,
    )
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kaggle": {
                "accelerator": "gpu",
                "dataSources": [],
                "isGpuEnabled": True,
                "isInternetEnabled": True,
                "language": "python",
            },
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
        },
        "cells": [
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": source.split("\n"),
            }
        ],
    }
    return notebook


def generate_video_kaggle(
    prompt: str,
    frames: int = 49,
) -> dict[str, Any]:
    """Generate video using CogVideoX on Kaggle GPU."""
    if not _check_kaggle():
        return {
            "status": "notebook_ready",
            "tool": "CogVideoX",
            "prompt": prompt,
            "frames": frames,
            "duration_seconds": round(frames / 8, 1),
            "estimated_time": "~3-5 minutes on T4 GPU",
            "notebook": _build_cogvideo_notebook(prompt, frames),
            "notebook_code": COGVIDEO_NOTEBOOK_SOURCE.format(
                prompt=prompt, frames=frames
            ),
            "message": "Kaggle CLI not found. Notebook ready for manual upload.",
        }

    # Submit via Kaggle API
    notebook_data = _build_cogvideo_notebook(prompt, frames)
    import tempfile
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".ipynb", delete=False, dir=tempfile.gettempdir()
    ) as f:
        json.dump(notebook_data, f)
        tmp_path = f.name

    try:
        creds = _get_kaggle_creds()
        result = _run_kaggle_cmd(
            ["kernels", "push", "-p", tmp_path, "-t", "gpu"],
            timeout=30,
        )
        if result["success"]:
            kernel_slug = f"{creds.get('username', 'user')}/tags-cogvideo-{int(time.time())}"
            return {
                "status": "submitted",
                "tool": "CogVideoX",
                "prompt": prompt,
                "frames": frames,
                "duration_seconds": round(frames / 8, 1),
                "estimated_time": "~3-5 minutes on T4 GPU",
                "kernel_slug": kernel_slug,
                "message": "Notebook submitted to Kaggle.",
                "check_status": f"kaggle kernels status {kernel_slug}",
            }
        else:
            return {
                "status": "submit_failed",
                "error": result.get("stderr", result.get("error", "Unknown")),
                "notebook_code": COGVIDEO_NOTEBOOK_SOURCE.format(
                    prompt=prompt, frames=frames
                ),
            }
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
# ═══════════════════════════════════════════════════════════════════════════════
# 3. AD CREATIVE IMAGES
# ═══════════════════════════════════════════════════════════════════════════════

def generate_ad_image(
    product: str,
    platform: str = "facebook",
    style: str = "professional",
) -> dict[str, Any]:
    """Generate ad creative image using FLUX on Kaggle."""
    size_map = {
        "facebook": (1200, 628),
        "instagram": (1080, 1080),
        "google": (1200, 628),
        "linkedin": (1200, 627),
        "youtube": (1280, 720),
    }
    width, height = size_map.get(platform, (1200, 628))

    style_map = {
        "professional": "clean, professional, modern, corporate",
        "bold": "bold, vibrant, eye-catching, dynamic",
        "minimal": "minimalist, clean, white space, elegant",
        "creative": "creative, artistic, unique, memorable",
    }
    style_desc = style_map.get(style, style_map["professional"])

    prompt = (
        f"A professional {style} advertisement for {product}, "
        f"{style_desc}, high quality, marketing material, text overlay space"
    )

    return generate_image_kaggle(prompt, width, height)


# ═══════════════════════════════════════════════════════════════════════════════
# 4. SOCIAL MEDIA IMAGES
# ═══════════════════════════════════════════════════════════════════════════════

def generate_social_image(
    topic: str,
    platform: str = "instagram",
) -> dict[str, Any]:
    """Generate social media image using FLUX on Kaggle."""
    size_map = {
        "instagram": (1080, 1080),
        "facebook": (1200, 630),
        "twitter": (1200, 675),
        "linkedin": (1200, 627),
        "youtube": (1280, 720),
        "pinterest": (1000, 1500),
    }
    width, height = size_map.get(platform, (1080, 1080))

    prompt = (
        f"A beautiful, engaging social media post about {topic}, "
        f"modern design, vibrant colors, professional quality"
    )

    return generate_image_kaggle(prompt, width, height)


# ═══════════════════════════════════════════════════════════════════════════════
# 5. BLOG/WEBSITE HERO IMAGES
# ═══════════════════════════════════════════════════════════════════════════════

def generate_hero_image(
    topic: str,
    style: str = "modern",
) -> dict[str, Any]:
    """Generate hero/banner image for blog or website."""
    prompt = (
        f"A stunning hero banner image about {topic}, {style} design, "
        f"wide format, professional quality, clean composition"
    )

    return generate_image_kaggle(prompt, width=1920, height=1080)


# ═══════════════════════════════════════════════════════════════════════════════
# 6. VIDEO ADS
# ═══════════════════════════════════════════════════════════════════════════════

def generate_video_ad(
    product: str,
    duration: str = "short",
) -> dict[str, Any]:
    """Generate video ad using CogVideoX on Kaggle."""
    frames_map = {"short": 49, "medium": 81, "long": 113}
    frames = frames_map.get(duration, 49)

    prompt = (
        f"A compelling video advertisement for {product}, dynamic, "
        f"professional, engaging, marketing quality"
    )

    return generate_video_kaggle(prompt, frames)


# ═══════════════════════════════════════════════════════════════════════════════
# 7. BATCH GENERATE (for content calendar)
# ═══════════════════════════════════════════════════════════════════════════════

def batch_generate_images(
    topics: list[str],
    platform: str = "instagram",
) -> dict[str, Any]:
    """Generate multiple images for a content calendar."""
    results = []
    for topic in topics[:5]:
        result = generate_social_image(topic, platform)
        results.append({
            "topic": topic,
            "status": result.get("status", "unknown"),
            "notebook_code": result.get("notebook_code", ""),
        })

    return {
        "total": len(results),
        "platform": platform,
        "images": results,
        "note": "Run each notebook on Kaggle to generate images",
    }


# ═══════════════════════════════════════════════════════════════════════════════
# 8. CHECK NOTEBOOK STATUS
# ═══════════════════════════════════════════════════════════════════════════════

def check_notebook_status(kernel_slug: str) -> dict[str, Any]:
    """Check status of a submitted Kaggle notebook."""
    if not _check_kaggle():
        return {"status": "error", "message": "Kaggle CLI not installed"}

    result = _run_kaggle_cmd(["kernels", "status", kernel_slug])
    if result["success"]:
        return {
            "status": "checked",
            "kernel_slug": kernel_slug,
            "output": result["stdout"],
        }
    return {
        "status": "error",
        "kernel_slug": kernel_slug,
        "error": result.get("stderr", "Unknown error"),
    }


def download_notebook_output(kernel_slug: str) -> dict[str, Any]:
    """Download output from a completed Kaggle notebook."""
    if not _check_kaggle():
        return {"status": "error", "message": "Kaggle CLI not installed"}

    import tempfile
    output_dir = tempfile.mkdtemp(prefix="kaggle_output_")
    result = _run_kaggle_cmd(
        ["kernels", "pull", kernel_slug, "-p", output_dir],
        timeout=60,
    )
    if result["success"]:
        return {
            "status": "downloaded",
            "kernel_slug": kernel_slug,
            "output_dir": output_dir,
            "files": os.listdir(output_dir) if os.path.exists(output_dir) else [],
        }
    return {
        "status": "error",
        "kernel_slug": kernel_slug,
        "error": result.get("stderr", "Unknown error"),
    }


# ═══════════════════════════════════════════════════════════════════════════════
# TOOL REGISTRY
# ═══════════════════════════════════════════════════════════════════════════════

KAGGLE_TOOLS = [
    {
        "name": "generate_image_kaggle",
        "description": "Generate AI image using FLUX on Kaggle GPU. Free 30hrs/week quota.",
        "parameters": {
            "type": "object",
            "properties": {
                "prompt": {"type": "string", "description": "Image description"},
                "width": {"type": "integer", "description": "Width in pixels", "default": 1024},
                "height": {"type": "integer", "description": "Height in pixels", "default": 1024},
                "steps": {"type": "integer", "description": "Inference steps (more=better, slower)", "default": 20},
            },
            "required": ["prompt"],
        },
    },
    {
        "name": "generate_video_kaggle",
        "description": "Generate AI video using CogVideoX on Kaggle GPU.",
        "parameters": {
            "type": "object",
            "properties": {
                "prompt": {"type": "string", "description": "Video description"},
                "frames": {"type": "integer", "description": "Number of frames (49=~6s, 81=~10s)", "default": 49},
            },
            "required": ["prompt"],
        },
    },
    {
        "name": "generate_ad_image",
        "description": "Generate ad creative image for specific platform.",
        "parameters": {
            "type": "object",
            "properties": {
                "product": {"type": "string", "description": "Product/service to advertise"},
                "platform": {"type": "string", "description": "Target platform", "default": "facebook"},
                "style": {"type": "string", "description": "Style: professional, bold, minimal, creative", "default": "professional"},
            },
            "required": ["product"],
        },
    },
    {
        "name": "generate_social_image",
        "description": "Generate social media post image for specific platform.",
        "parameters": {
            "type": "object",
            "properties": {
                "topic": {"type": "string", "description": "Post topic"},
                "platform": {"type": "string", "description": "Target platform", "default": "instagram"},
            },
            "required": ["topic"],
        },
    },
    {
        "name": "generate_hero_image",
        "description": "Generate hero/banner image for blog or website.",
        "parameters": {
            "type": "object",
            "properties": {
                "topic": {"type": "string", "description": "Hero image topic"},
                "style": {"type": "string", "description": "Style: modern, minimal, bold", "default": "modern"},
            },
            "required": ["topic"],
        },
    },
    {
        "name": "generate_video_ad",
        "description": "Generate video advertisement using CogVideoX on Kaggle.",
        "parameters": {
            "type": "object",
            "properties": {
                "product": {"type": "string", "description": "Product/service to advertise"},
                "duration": {"type": "string", "description": "Duration: short(6s), medium(10s), long(14s)", "default": "short"},
            },
            "required": ["product"],
        },
    },
    {
        "name": "batch_generate_images",
        "description": "Generate multiple images for content calendar (up to 5).",
        "parameters": {
            "type": "object",
            "properties": {
                "topics": {"type": "array", "items": {"type": "string"}, "description": "List of topics"},
                "platform": {"type": "string", "description": "Target platform", "default": "instagram"},
            },
            "required": ["topics"],
        },
    },
]


def execute_kaggle_tool(tool_name: str, params: dict[str, Any]) -> dict[str, Any]:
    """Execute a Kaggle tool by name."""
    tool_map = {
        "generate_image_kaggle": lambda p: generate_image_kaggle(
            p["prompt"], p.get("width", 1024), p.get("height", 1024), p.get("steps", 20)
        ),
        "generate_video_kaggle": lambda p: generate_video_kaggle(
            p["prompt"], p.get("frames", 49)
        ),
        "generate_ad_image": lambda p: generate_ad_image(
            p["product"], p.get("platform", "facebook"), p.get("style", "professional")
        ),
        "generate_social_image": lambda p: generate_social_image(
            p["topic"], p.get("platform", "instagram")
        ),
        "generate_hero_image": lambda p: generate_hero_image(
            p["topic"], p.get("style", "modern")
        ),
        "generate_video_ad": lambda p: generate_video_ad(
            p["product"], p.get("duration", "short")
        ),
        "batch_generate_images": lambda p: batch_generate_images(
            p["topics"], p.get("platform", "instagram")
        ),
        "check_notebook_status": lambda p: check_notebook_status(p["kernel_slug"]),
        "download_notebook_output": lambda p: download_notebook_output(p["kernel_slug"]),
    }
    if tool_name not in tool_map:
        return {"error": f"Unknown tool: {tool_name}"}
    return tool_map[tool_name](params)
