"""Email sending utility for TAGS Agency.

Sends reports, alerts, and notifications via SMTP.
Supports: Gmail, Outlook, custom SMTP servers.
"""
from __future__ import annotations

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Default SMTP config (Gmail)
DEFAULT_SMTP = {
    "host": "smtp.gmail.com",
    "port": 587,
    "use_tls": True,
}


def send_email(
    to: list[str],
    subject: str,
    body: str,
    body_html: str | None = None,
    from_email: str | None = None,
    from_password: str | None = None,
    smtp_host: str | None = None,
    smtp_port: int | None = None,
    cc: list[str] | None = None,
    bcc: list[str] | None = None,
) -> dict[str, Any]:
    """Send email via SMTP.

    Args:
        to: List of recipient email addresses
        subject: Email subject line
        body: Plain text body
        body_html: Optional HTML body (for rich formatting)
        from_email: Sender email (uses env TAGS_SMTP_EMAIL if not provided)
        from_password: SMTP password/app password (uses env TAGS_SMTP_PASSWORD)
        smtp_host: SMTP server host
        smtp_port: SMTP server port
        cc: CC recipients
        bcc: BCC recipients

    Returns:
        dict with status, recipients count, etc.
    """
    import os

    sender = from_email or os.getenv("TAGS_SMTP_EMAIL", "")
    password = from_password or os.getenv("TAGS_SMTP_PASSWORD", "")
    host = smtp_host or os.getenv("TAGS_SMTP_HOST", DEFAULT_SMTP["host"])
    port = smtp_port or int(os.getenv("TAGS_SMTP_PORT", str(DEFAULT_SMTP["port"])))

    if not sender or not password:
        logger.warning("Email not configured — TAGS_SMTP_EMAIL / TAGS_SMTP_PASSWORD missing")
        return {
            "status": "not_configured",
            "message": "SMTP credentials not set. Set TAGS_SMTP_EMAIL and TAGS_SMTP_PASSWORD in .env",
            "recipients": len(to),
        }

    # Build message
    msg = MIMEMultipart("alternative")
    msg["From"] = sender
    msg["To"] = ", ".join(to)
    msg["Subject"] = subject
    if cc:
        msg["Cc"] = ", ".join(cc)

    # Plain text part
    msg.attach(MIMEText(body, "plain"))

    # HTML part (if provided)
    if body_html:
        msg.attach(MIMEText(body_html, "html"))

    # Collect all recipients
    all_recipients = list(to)
    if cc:
        all_recipients.extend(cc)
    if bcc:
        all_recipients.extend(bcc)

    try:
        with smtplib.SMTP(host, port) as server:
            server.starttls()
            server.login(sender, password)
            server.sendmail(sender, all_recipients, msg.as_string())

        logger.info("Email sent to %d recipients: %s", len(to), subject)
        return {
            "status": "sent",
            "recipients": len(to),
            "cc": len(cc) if cc else 0,
            "bcc": len(bcc) if bcc else 0,
            "subject": subject,
        }

    except smtplib.SMTPAuthenticationError:
        logger.error("SMTP auth failed — check email/password")
        return {"status": "auth_error", "message": "SMTP authentication failed"}
    except smtplib.SMTPException as e:
        logger.error("SMTP error: %s", e)
        return {"status": "smtp_error", "message": str(e)}
    except Exception as e:
        logger.error("Email send failed: %s", e)
        return {"status": "error", "message": str(e)}


def send_report_email(
    to: list[str],
    report_title: str,
    report_body: str,
    report_html: str | None = None,
    workspace_name: str = "",
    client_name: str = "",
    report_type: str = "weekly",
    cc: list[str] | None = None,
    bcc: list[str] | None = None,
) -> dict[str, Any]:
    """Send a formatted report email.

    Wraps send_email with TAGS Agency branding.
    """
    subject = f"[TAGS Agency] {report_title}"

    # Plain text version
    body = (
        f"TAGS Agency — Performance Report\n"
        f"{'=' * 50}\n\n"
        f"Workspace: {workspace_name}\n"
        f"Client: {client_name}\n"
        f"Report Type: {report_type}\n\n"
        f"{'─' * 50}\n\n"
        f"{report_body}\n\n"
        f"{'─' * 50}\n"
        f"Generated by TAGS Agency Analytics Agent\n"
        f"https://tags-agency.vercel.app\n"
    )

    # HTML version (if not provided, use basic)
    if not report_html:
        report_html = (
            f"<div style='font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto;'>"
            f"<div style='background: #1a1a2e; color: white; padding: 20px; text-align: center;'>"
            f"<h1 style='margin: 0;'>TAGS Agency</h1>"
            f"<p style='margin: 5px 0 0;'>Analytics Report</p>"
            f"</div>"
            f"<div style='padding: 20px; background: #f8f9fa;'>"
            f"<p><strong>Workspace:</strong> {workspace_name}</p>"
            f"<p><strong>Client:</strong> {client_name}</p>"
            f"<p><strong>Report:</strong> {report_type.title()}</p>"
            f"<hr/>"
            f"<pre style='white-space: pre-wrap; font-size: 14px;'>{report_body}</pre>"
            f"</div>"
            f"<div style='text-align: center; padding: 10px; color: #888; font-size: 12px;'>"
            f"Generated by TAGS Agency Analytics Agent"
            f"</div>"
            f"</div>"
        )

    return send_email(
        to=to,
        subject=subject,
        body=body,
        body_html=report_html,
        cc=cc,
        bcc=bcc,
    )


def send_alert_email(
    to: list[str],
    alert_type: str,
    message: str,
    severity: str = "medium",
    workspace_name: str = "",
    client_name: str = "",
) -> dict[str, Any]:
    """Send an alert email for anomalies/issues."""
    severity_emoji = {
        "low": "ℹ️",
        "medium": "⚠️",
        "high": "🚨",
        "critical": "🔴",
    }
    emoji = severity_emoji.get(severity, "⚠️")
    subject = f"{emoji} [TAGS Agency] {alert_type} — {workspace_name}"

    body = (
        f"TAGS Agency — Alert\n"
        f"{'=' * 50}\n\n"
        f"Severity: {severity.upper()}\n"
        f"Workspace: {workspace_name}\n"
        f"Client: {client_name}\n"
        f"Alert: {alert_type}\n\n"
        f"Details:\n{message}\n\n"
        f"{'─' * 50}\n"
        f"TAGS Agency Analytics Agent\n"
    )

    return send_email(to=to, subject=subject, body=body)
